#ifndef _USOUND_H_
#define _USOUND_H_

#include "ti_msp_dl_config.h"

#if defined GPIO_CAPTURE_ULTRASONIC_C0_PORT
#define CAPTURE_ULTRASONIC_CC_IDX DL_TIMER_CC_0_INDEX
#elif defined GPIO_CAPTURE_ULTRASONIC_C1_PORT
#define CAPTURE_ULTRASONIC_CC_IDX DL_TIMER_CC_1_INDEX
#elif defined GPIO_CAPTURE_ULTRASONIC_C2_PORT
#define CAPTURE_ULTRASONIC_CC_IDX DL_TIMER_CC_2_INDEX
#elif defined GPIO_CAPTURE_ULTRASONIC_C3_PORT
#define CAPTURE_ULTRASONIC_CC_IDX DL_TIMER_CC_3_INDEX
#elif defined GPIO_CAPTURE_ULTRASONIC_C4_PORT
#define CAPTURE_ULTRASONIC_CC_IDX DL_TIMER_CC_4_INDEX
#elif defined GPIO_CAPTURE_ULTRASONIC_C5_PORT
#define CAPTURE_ULTRASONIC_CC_IDX DL_TIMER_CC_5_INDEX
#endif

uint16_t Read_usound(void);

#endif